### ISSUE TITLE
Monitored Conditions

### ISSUE THREAD

**Issue by jchasey** [glpatcern/domotica#2]
With the addition of heating, hot_water etc, listing every sensor in the setup for Monitored Conditions gets pretty large. Howabout instead simply listing the OWL Class of the sensors that you want to monitor, then all the sensors for that class are created at setup?

**Comment by glpatcern** [comment]
Yep, why not. I guess the classes could be:
```
OWLCLASS_ELECTRICITY    # including current SENSOR_BATTERY, _RADIO, _POWER, _ENERGY_TODAY
OWLCLASS_SOLARGEN       # including the current SOLAR* ones
OWLCLASS_HEATING        # your call
OWLCLASS_HOTWATER       # your call
```
Still, the `SENSOR_TYPES` array must be populated to reflect all 'sub-sensors' and their icons etc., but this can be kept internal and not exposed in the HA configuration.
Also, I think the code should still be centralized in a single `OwlIntuitionSensor` class with more if cases.

**Comment by jchasey** [comment]
Yes that would work - we can then add additional battery and radio sensors for each class to reflect the battery and radio state of the respective devices.
e.g.:

```
SENSOR_ELECTRICITY_BATTERY
SENSOR_ELECTRICITY_RADIO
SENSOR_HEATING_BATTERY
SENSOR_HEATING_RADIO
SENSOR_HOTWATER_BATTERY
SENSOR_HOTWATER_RADIO
```

We can also add a RELAY class as you may want to monitor the battery status of a relay unit.

**Comment by glpatcern** [comment]
Sounds good :) for the solar part, I can ask the guy that gave me the XML data (I don't have the device myself).

**Comment by glpatcern** [comment]
PR #3, follow up at https://github.com/custom-components/sensor.owlintuition
