### ISSUE TITLE
Integrate with custom component tracker

### ISSUE THREAD

**Issue by jchasey** [glpatcern/domotica#4]
Also suggest that the codebase is moved to the repo (https://github.com/custom-components).

Then we can make use of the custom component updater to automatically update as required, prior to any full integration into HA. Given the async issue it may take a while to solve that and it would then be easier to install and maintain in the meantime.

**Comment by glpatcern** [comment]
Didn't know about that 'semi-official' repo, that sounds like a very good idea indeed.
Let me try and extract the full git history as the async attempts are there and I'd prefer to keep them as opposed to just push the current file.

**Comment by glpatcern** [comment]
(I'm still waiting to get access to the custom-components repo - once it's ok, I'll push all the code there including your PR)

**Comment by glpatcern** [comment]
Done at https://github.com/custom-components/sensor.owlintuition
